info:
  name: gitMonitor
  author: Ultra119
  version: 1.0
  description: Module for commits monitoring
  python: 3.13

permissions:
  - require_db

config:
  api_token: ""  # Place for YOUR GitHub API Token
  default_check_interval: 60  # Default interval in seconds between checks
  max_retries: 5  # Maximum number of retries after network errors
